spring:
  application:
    name: msavaliadorcredito
  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: 5672
    username: guest
    password: guest

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://cursoms-eureka-user:russeruasrk-oec-meu@${EUREKA_SERVER}:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.application.instanceId:${random.value}}

mq:
  queues:
    emissao-cartoes: emissao-cartoes

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log