spring:
  application:
    name: eurekaserver
  security:
    basic:
      enable: true
    user:
      name: cursoms-eureka-user
      password: russeruasrk-oec-meu

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
