spring:
  application:
    name: msclientes

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://cursoms-eureka-user:russeruasrk-oec-meu@localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.application.instanceId:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log